[font]
size = 14.0
normal = { family = "FiraCodeNerdFontMono", style = "Regular" }
bold = { family = "FiraCodeNerdFontMono", style = "Bold" }
italic = { family = "FiraCodeNerdFontMono", style = "Italic" }
bold_italic = { family = "FiraCodeNerdFontMono", style = "Bold italic" }
offset = { x = 0, y = 12 }
glyph_offset = { x = 0, y = 6 }

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_padding = true

[colors]
[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black = "#272727"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
