[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "typescript"
#language-id	= "typescript"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
indent = { tab-width = 2, unit = "  " }
#language-servers = [ "typescript-language-server" ]
