- name: Install yay (AUR helper)
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: true

    - name: Install dependencies
      package:
        name:
          - git
          - base-devel
        state: present

    - name: Clone the yay repository from AUR
      git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: /home/jofre/.dotfiles/config/ansible/tmp/yay
        update: yes
        version: HEAD
      become: true
      become_user: jofre

    - name: Build and install yay
      command: "makepkg -si --noconfirm"
      args:
        chdir: ~/temp/yay
      become: true
      become_user: jofre

    - name: Clean up temporary directory
      file:
        path: /home/jofre/.dotfiles/config/ansible/tmp/yay
        state: absent
        force: yes

    - name: Install AUR packages with yay
      shell: yay -Syu --noconfirm "{{ item }}"
      with_items:
        - dmenu-wayland-git
        - google-chrome
        - hyprpicker
        - logseq-desktop-bin
      become: true
      become_user: jofre
