- name: Bluetooth setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: true

    - name: Install packages
      package:
        name:
          - bluez
          - bluez-utils
        state: present

    - name: Enable bluetooth
      ansible.builtin.service:
        name: bluetooth
        enabled: true
