- name: Link multiple configurations
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    configs:
      - { src: /home/jofre/.dotfiles/config/fontconfig, dest: /home/jofre/.config/fontconfig }
      - { src: /home/jofre/.dotfiles/config/alacritty, dest: /home/jofre/.config/alacritty }
      - { src: /home/jofre/.dotfiles/config/ansible, dest: /home/jofre/.config/ansible }
      - { src: /home/jofre/.dotfiles/config/nvim, dest: /home/jofre/.config/nvim }
      - { src: /home/jofre/.dotfiles/config/fish, dest: /home/jofre/.config/fish }
      - { src: /home/jofre/.dotfiles/config/tmux, dest: /home/jofre/.config/tmux }
      - { src: /home/jofre/.dotfiles/config/hypr, dest: /home/jofre/.config/hypr }
      - { src: /home/jofre/.dotfiles/ssh/config, dest: /home/jofre/.ssh/config }

    extra_configs:
      - { src: /home/jofre/.dotfiles/sudoers, dest: /etc/sudoers }

  tasks:
    - name: Clone the dotfiles if not already present
      git:
        repo: 'https://github.com/Jofr3/.dotfiles'
        dest: /home/jofre/.dotfiles/
        clone: yes
        update: no  

    - name: Ensure the destination directory exists
      file:
        path: /home/jofre/.config
        state: directory
        owner: jofre
        group: jofre

    - name: Remove existing configurations if they exist
      file:
        path: "{{ item.dest }}"
        state: absent
        force: yes
      loop: "{{ configs }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Create symbolic links for configurations
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ configs }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Remove extra existing configurations if they exist
      file:
        path: "{{ item.dest }}"
        state: absent
        force: yes
      loop: "{{ extra_configs }}"
      loop_control:
        label: "{{ item.dest }}"

    - name: Link extra configurations
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0440
      loop: "{{ extra_configs }}"
      loop_control:
        label: "{{ item.dest }}"
