- name: Initial system setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Install FiraCode Mono
      block: 
        - name: Ensure font directory exists
          file:
            path: /home/jofre/.local/share/fonts
            state: directory
            owner: jofre
            group: jofre

        - name: Create a temporary directory for font binaries
          file:
            path: /home/jofre/temp
            state: directory

        - name: Download the font binaries
          get_url:
            url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip"
            dest: "/home/jofre/temp"

        - name: Unzip the font binaries
          unarchive:
            src: "/home/jofre/temp/FiraCode.zip"
            dest: "/home/jofre/temp"

        - name: Delete the ZIP file
          file:
            path: "/home/jofre/temp/FiraMono.zip"
            state: absent

        - name: Copy the fonts binaries to the fonts folder
          shell: mv /home/jofre/temp/FiraCode* /home/jofre/.local/share/fonts

        - name: Reload the font cache
          command: fc-cache -f -v

        - name: Delete the temporary folder
          file:
            path: "/home/jofre/temp"
            state: absent

    # - name: Install Icons
    #   block: 
    #     - name: Ensure font directory exists
    #       file:
    #         path: /home/jofre/.local/share/fonts
    #         state: directory
    #
    #     - name: Create a temporary directory for font binaries
    #       file:
    #         path: /home/jofre/temp
    #         state: directory
    #
    #     - name: Download the font binaries
    #       get_url:
    #         url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/NerdFontsSymbolsOnly.zip"
    #         dest: "/home/jofre/temp"
    #
    #     - name: Unzip the font binaries
    #       unarchive:
    #         src: "/home/jofre/temp/NerdFontsSymbolsOnly.zip"
    #         dest: "/home/jofre/temp"
    #
    #     - name: Delete the ZIP file
    #       file:
    #         path: "/home/jofre/temp/NerdFontsSymbolsOnly.zip"
    #         state: absent
    #
    #     - name: Copy the fonts binaries to the fonts folder
    #       shell: mv /home/jofre/temp/SymbolsNerdFont* /home/jofre/.local/share/fonts
    #
    #     - name: Reload the font cache
    #       command: fc-cache -f -v
    #
    #     - name: Delete the temporary folder
    #       file:
    #         path: "/home/jofre/temp"
    #         state: absent
    #
