- name: Display manager setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: false

    - name: Install packages
      package:
        name: gdm
        state: present

    - name: Enable display manager
      ansible.builtin.service:
        name: gdm
        enabled: true
