- name: Network setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Ensure NetworkManager is installed
      package:
        name: networkmanager
        state: present

    - name: Ensure NetworkManager is running
      service:
        name: NetworkManager
        state: started
        enabled: true

    - name: Configure WiFi connection
      community.general.nmcli:
        conn_name: 'WIFI'
        ifname: 'wlan0'
        type: wifi
        ssid: 'Vera_C326AB'
        wifi_password: 'cab6533559'
        state: present

    - name: Restart NetworkManager to apply changes
      service:
        name: NetworkManager
        state: restarted
