- name: Network setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: false

    - name: Ensure NetworkManager is installed
      package:
        name: networkmanager
        state: present

    - name: Ensure NetworkManager is running
      service:
        name: NetworkManager
        state: started
        enabled: true

    - name: Configure WiFi connection
      shell: nmcli device wifi connect Vera_C326AB password cab6533559

    - name: Restart NetworkManager to apply changes
      service:
        name: NetworkManager
        state: restarted
