- name: Install packages with dependencies
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

    package_groups:
      - group: "Hyprland and its dependencies"
        packages:
          - hyprland
          - hyprpaper
          - hyprcursor
          - wl-clipboard
          - brightnessctl
          - dmenu
          - grim
          - slurp
          - nautilus
          - evince
          - eog
          - gnome-text-editor
          - totem
      - group: "Alacitty and its dependencies"
        packages:
          - alacritty
          - fastfetch
          - zoxide
          - fish
          - tmux
          - eza
      - group: "Neovim and its dependencies"
        packages:
          - neovim
          - fzf
          - ripgrep
          - fd
          - wget
          - rust
          - composer
          - php
          - npm
          - nodejs
          - jdk-openjdk
          - julia
          - go
          - luarocks
          - ruby
          - python-pip
          - tree-sitter
          - python
          - perl
          - lua-jsregexp
      - group: "Audio"
        packages:
          - alsa-utils
          - alsa-plugins
          - alsa-firmware
          - sof-firmware
          - pipewire
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
      - group: "Other"
        packages:
          - nix
          - docker
          - docker-compose
          - chromium
          - base-devel
          - openssh
          - onefetch

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: true

    - name: Install packages
      package:
        name: "{{ item.packages }}"
        state: present
      loop: "{{ package_groups }}"
      loop_control:
        label: "{{ item.group }}"
