- name: Initial system setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Ensure user default shell is fish
      user:
        name: jofre
        shell: /usr/bin/fish
        state: present
