- name: Initial system setup
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fetch for package updates
      package:
        update_cache: true
        upgrade: false

    - name: Install fish shell
      package:
        name: fish
        state: present

    - name: Ensure user default shell is fish
      user:
        name: jofre
        shell: /usr/bin/fish
        state: present
