// GENERATED by `bun run scripts/catalog-manifest.ts` — DO NOT EDIT BY HAND.
//
// The committed measurement of the local D1 (D156). Every catalog claim the
// engine's comments and fixtures make is checked against this file by
// `catalogManifest.test.ts`; the sqlite itself is read only by the generator,
// because it is `.wrangler/` dev state and may be absent or stale on any other
// machine (see the script's header for the tradeoff that buys).
//
//   select set_id, count(*) from cards group by set_id;   -- sv01|258  sv02|279  sv03|230  sv06.5|99  sve|24  swsh10.5|88
//   select count(*) from cards;                           -- 978
//
// TEST-ONLY: not exported from the package index, exactly like `testFixtures.ts`.

/** The catalog census, MEASURED — never copied forward, and never quoted without
    its SCOPE. `rows`/`sets` describe the file on disk today. `history` describes
    the interval in which it held ONE SET FEWER: a census comment dated 2026-08-03
    was measuring THAT population, and its counts are floors against this one.
    Both are real; what was missing from ~20 comments was which one they meant. */
export const CATALOG_MANIFEST = {
  /** Which file the numbers below describe. `mtime` is the sqlite's last write,
      NOT the day the manifest was generated — the catalog is ingest output and
      does not drift on its own, so the mtime is the honest provenance. */
  source: {
    path: "apps/api/.wrangler/state/v3/d1/miniflare-D1DatabaseObject/8437d86672ef67002c76a06d8e29643de1a9c95e9422816cce0e554c6c5b7286.sqlite",
    mtime: "2026-08-03T09:22:30.953Z",
    bytes: 708608,
    generated: "2026-08-04",
  },
  /** `select count(*) from cards`. */
  rows: 978,
  /** `select set_id, count(*) from cards group by set_id` — THE SCOPE, and the
      first thing a census owes (D154). Six sets, `swsh10.5` among them
      again since the re-ingest recorded in `history` below; a census dated
      2026-08-03 saw the other five ONLY, which is what that block exists to say. */
  sets: {
    "sv01": 258,
    "sv02": 279,
    "sv03": 230,
    "sv06.5": 99,
    "sve": 24,
    "swsh10.5": 88,
  } as Record<string, number>,
  /** `select category, count(*) from cards group by category`. */
  categories: {
    "Energy": 35,
    "Pokemon": 810,
    "Trainer": 133,
  } as Record<string, number>,
  /** `select count(distinct name) from cards` — a card is a PRINTING, so this
      is well below `rows` (D135/D145: two printings can agree on everything but
      the set and the attacks). */
  distinctNames: 567,
  /** The THREE text columns a census must search. Every one of them has been
      missed by a census that searched only one, which is why they are counted
      separately here: rows where the column is present and non-empty. */
  textColumns: {
    effect: 137,
    attacksJson: 809,
    abilitiesJson: 160,
    /** Rows carrying text in AT LEAST ONE of the three — the real denominator
        for "N printings out of M" claims. */
    any: 947,
  },
  /** Rows whose `attacks_json` contains a STRAIGHT apostrophe (U+0027) — the
      population D137's apostrophe fold is about. */
  straightApostropheInAttacks: 359,
  /** Rows carrying a CURLY apostrophe (U+2019) in `effect`, `attacks_json`,
      `abilities_json` or `name`. D137's claim is that this is ZERO — the fold
      exists against a future re-ingest, not against today's bytes. */
  curlyApostropheAnywhere: 0,
  /** `select count(*) from cards where legal_standard = 0` — D113's "not a
      slice-selection criterion" number, and one of the four axes on which the
      restoration reconciles (851 − 88 = 763, the count D156
      committed for the shrunken catalog). */
  legalStandardZero: 851,
  /** Pokémon rows carrying NO attacks at all, by id. ⚠️ D156 ASSERTED THIS WAS
      EMPTY — `attacksJson` equals the `Pokemon` category count — and that was
      true of the FIVE-set catalog and is FALSE of this one. The restored set
      brought the counterexample with it, so the claim is now a measured list
      rather than an equality: a Pokémon whose Ability borrows its attacks from
      elsewhere prints none of its own. */
  pokemonWithoutAttacks: ["swsh10.5-053"] as readonly string[],
  /** Rows in `sets` and `series`. A card's `set_id` FKs to `sets` and a set's
      `serie_id` to `series`, so a set is a row in all three tables — which is
      what made the loss recorded below a STRUCTURAL fact rather than a filtered
      query, and what makes the restoration one too (`serieRows` went 1 → 2: the
      `swsh` serie had to come back before its set could). */
  setRows: 6,
  serieRows: 2,
  /** ⚠️ THE SET THIS CATALOG LOST AND GOT BACK — HISTORY, NOT A LIVE DIVERGENCE
      (D160). Read this block as a record of an episode that is OVER: the counts
      above are the six-set catalog, exactly as ~20 census comments always said.

      WHAT HAPPENED. D112 (2026-08-01) wrote the breakdown down explicitly: *"The
      local pool is 978 cards over SIX sets, not 890 over five —
      sv01/sv02/sv03/sv06.5/sve PLUS swsh10.5 (Pokémon GO, 88 cards, reg-mark F,
      legal_standard=0), which every prior census silently omitted."* D147
      (2026-08-02) lists Pidove `swsh10.5-061` as a QUERY RESULT, so the rows were
      still there that day. D154 (2026-08-03) is the first slice to find them gone
      — no `cards` rows, no `sets` row, no `series` row, and the main .sqlite's
      mtime unmoved: the ingest had lived in a write-ahead log that was never
      checkpointed. D155 read the survivors' "978" as fiction; D156 proved by
      arithmetic that it had been a MEASUREMENT and built this manifest so a
      scopeless count could never pass again. **D160 re-ingested the set and
      checkpointed it (`PRAGMA wal_checkpoint(TRUNCATE)`), which is why `rows` is
      978 and `setRows` is 6 above.**

      ⚠️ WHY THE BLOCK STAYS AFTER THE RESTORE, WHICH IS THE WHOLE POINT. The rows
      came back; the COMMENTS WRITTEN WHILE THEY WERE GONE did not change. Every
      census in this repo dated 2026-08-03 — D154's, D155's, D156's own, and
      D157's, D158's and D159's, which all state "890 rows / 5 sets" in their own
      headers — queried `shrunken`. **Those counts are FLOORS against this
      catalog, not totals**, and `censusedInTheGap` names who owes a re-run.
      D160 settled two of them by measurement: §D149's "5 printings" and §D151's
      "six rows" are BOTH exact against the restored catalog, and D155's downward
      corrections of them (to 4 and 5) were the outage speaking.

      ⚠️ AND THE RECONCILIATION IS BY SUBTRACTION ON FOUR AXES, NOT ONE.
      `contributes` is measured off today's file; `shrunken` is what D156
      committed. `live − contributes === shrunken` on rows, `legal_standard = 0`,
      rows-with-attacks and straight-apostrophe rows. A re-ingest that restored a
      DIFFERENT 88 rows would reconcile on the row count alone and fail the other
      three, which is the only check available for a population nothing can query
      any more. */
  history: {
    /** The set that went missing and returned. */
    set: "swsh10.5",
    /** Last date a census in this repo saw it (D147's table). */
    lastSeen: "2026-08-02",
    /** First date a census found it gone (D154). */
    firstMissing: "2026-08-03",
    /** Date it was re-ingested and the WAL checkpointed (D160). */
    restored: "2026-08-03",
    /** MEASURED off today's file: what `swsh10.5` contributes to each
        count above. The subtrahend of the reconciliation. */
    contributes: {
      rows: 88,
      legalStandardZero: 88,
      rowsWithAttacks: 73,
      straightApostropheInAttacks: 33,
    },
    /** RECORDED, NOT MEASURED — D156's committed census of the catalog during the
        outage, which nothing can query now. This is the population every census
        comment dated 2026-08-03 was actually describing. */
    shrunken: {
      rows: 890,
      setCount: 5,
      legalStandardZero: 763,
      rowsWithAttacks: 736,
      straightApostropheInAttacks: 326,
    },
    /** The decisions whose censuses ran against `shrunken` and are therefore
        FLOORS. A future session re-running any of these should say so. */
    censusedInTheGap: ["D154", "D155", "D156", "D157", "D158", "D159"] as readonly string[],
  },
  /** Every REAL-card fixture id in `FIXTURE_POOL` that HAS a catalog row, with
      the printed attack and Ability NAMES in printed ORDER. The order is
      load-bearing: an attack's INDEX is what the `attack` action, the registry's
      `attack` map and D154/D155's `attackIndex` all key on, and a fixture that
      drops a LEADING attack silently renumbers every one after it.

      `types` is here since D173, and it is the first field on this row that is
      NOT a list of names. It was added because the wrong-index sweep turned up a
      fixture (Klefki sv01-096) carrying a type the card does not print, and
      NOTHING in this repo could see it: the manifest only ever recorded names, so
      `catalogManifest.test.ts` could prove a fixture carried the right ATTACKS
      while it carried the wrong ELEMENT. A value no census records is a value no
      census can contradict. */
  printed: {
    "sv01-001": { name: "Pineco", types: ["Grass"], attacks: ["Guard Press"], abilities: [] },
    "sv01-002": { name: "Heracross", types: ["Grass"], attacks: ["Superpowered Throw","Horn Attack"], abilities: [] },
    "sv01-005": { name: "Cacnea", types: ["Grass"], attacks: ["Light Punch"], abilities: ["Counterattack Quills"] },
    "sv01-006": { name: "Cacturne", types: ["Grass"], attacks: ["Spike Shot"], abilities: ["Counterattack Quills"] },
    "sv01-007": { name: "Tropius", types: ["Grass"], attacks: ["Fresh-Picked Fruit","Razor Leaf"], abilities: [] },
    "sv01-018": { name: "Tarountula", types: ["Grass"], attacks: ["Surprise Attack"], abilities: [] },
    "sv01-019": { name: "Spidops ex", types: ["Grass"], attacks: ["Wire Hang"], abilities: ["Trap Territory"] },
    "sv01-023": { name: "Arboliva", types: ["Grass"], attacks: ["Solar Beam"], abilities: ["Enriching Oil"] },
    "sv01-029": { name: "Scovillain", types: ["Grass"], attacks: ["Hot Bite","Super Spicy Breath"], abilities: [] },
    "sv01-030": { name: "Growlithe", types: ["Fire"], attacks: ["Relentless Flames"], abilities: [] },
    "sv01-032": { name: "Arcanine ex", types: ["Fire"], attacks: ["Raging Claws","Bright Flame"], abilities: [] },
    "sv01-035": { name: "Torkoal", types: ["Fire"], attacks: ["Stampede","Concentrated Fire"], abilities: [] },
    "sv01-038": { name: "Skeledirge", types: ["Fire"], attacks: ["Passionate Singing","Blazing Shout"], abilities: [] },
    "sv01-039": { name: "Charcadet", types: ["Fire"], attacks: ["Ember"], abilities: [] },
    "sv01-041": { name: "Armarouge", types: ["Fire"], attacks: ["Flame Cannon"], abilities: ["Fire Off"] },
    "sv01-045": { name: "Gyarados ex", types: ["Water"], attacks: ["Waterfall","Tyrannical Tail"], abilities: [] },
    "sv01-048": { name: "Alomomola", types: ["Water"], attacks: ["Surf","Aqua Slash"], abilities: [] },
    "sv01-054": { name: "Quaquaval", types: ["Water"], attacks: ["Hydro Kick"], abilities: ["Energy Carnival"] },
    "sv01-056": { name: "Wiglett", types: ["Water"], attacks: ["Dig a Little","Ram"], abilities: [] },
    "sv01-057": { name: "Wugtrio", types: ["Water"], attacks: ["Headbutt","Undersea Tunnel"], abilities: [] },
    "sv01-060": { name: "Cetitan", types: ["Water"], attacks: ["Hammer In","Sweeping Tackle"], abilities: [] },
    "sv01-068": { name: "Pachirisu", types: ["Lightning"], attacks: ["Everyone Discharge"], abilities: ["Electricity Pouches"] },
    "sv01-069": { name: "Rotom", types: ["Lightning"], attacks: ["Linear Attack"], abilities: [] },
    "sv01-076": { name: "Pawmot", types: ["Lightning"], attacks: ["Electro Paws"], abilities: ["Electrogenesis"] },
    "sv01-079": { name: "Kilowattrel", types: ["Lightning"], attacks: ["Skill Dive","Thunder Blast"], abilities: [] },
    "sv01-080": { name: "Miraidon", types: ["Lightning"], attacks: ["Sharp Fang","Lightning Laser"], abilities: [] },
    "sv01-086": { name: "Gardevoir ex", types: ["Psychic"], attacks: ["Miracle Force"], abilities: ["Psychic Embrace"] },
    "sv01-089": { name: "Drifloon", types: ["Psychic"], attacks: ["Gust","Balloon Blast"], abilities: [] },
    "sv01-093": { name: "Florges", types: ["Psychic"], attacks: ["Moonblast"], abilities: ["Blooming Garden"] },
    "sv01-095": { name: "Dedenne", types: ["Psychic"], attacks: ["Second Bite"], abilities: [] },
    "sv01-096": { name: "Klefki", types: ["Psychic"], attacks: ["Joust"], abilities: ["Mischievous Lock"] },
    "sv01-099": { name: "Dachsbun", types: ["Psychic"], attacks: ["Headbutt Bounce"], abilities: ["Well-Baked Body"] },
    "sv01-105": { name: "Greavard", types: ["Psychic"], attacks: ["Underworld Stroll","Sharp Fang"], abilities: [] },
    "sv01-109": { name: "Annihilape", types: ["Fighting"], attacks: ["Rage Fist","Dynamite Punch"], abilities: [] },
    "sv01-111": { name: "Medicham", types: ["Fighting"], attacks: ["Acu-Punch-Ture","Kick Shot"], abilities: [] },
    "sv01-114": { name: "Lucario", types: ["Fighting"], attacks: ["Avenging Knuckle","Accelerating Stab"], abilities: [] },
    "sv01-116": { name: "Krokorok", types: ["Fighting"], attacks: ["Payback","Corkscrew Punch"], abilities: [] },
    "sv01-117": { name: "Krookodile", types: ["Fighting"], attacks: ["Chomp Chomp Bite","Earthquake"], abilities: [] },
    "sv01-118": { name: "Hawlucha", types: ["Fighting"], attacks: ["Wing Attack"], abilities: ["Flying Entry"] },
    "sv01-121": { name: "Stonjourner", types: ["Fighting"], attacks: ["Mega Kick"], abilities: ["Exoskeleton"] },
    "sv01-124": { name: "Koraidon", types: ["Fighting"], attacks: ["Claw Slash","Rampaging Fang"], abilities: [] },
    "sv01-125": { name: "Koraidon ex", types: ["Fighting"], attacks: ["Wild Impact"], abilities: ["Dino Cry"] },
    "sv01-128": { name: "Seviper", types: ["Darkness"], attacks: ["Spit Poison","Venoshock"], abilities: [] },
    "sv01-139": { name: "Forretress", types: ["Metal"], attacks: ["Continuous Spin","Rolling Shell"], abilities: [] },
    "sv01-142": { name: "Revavroom", types: ["Metal"], attacks: ["Knock Away"], abilities: ["Rumbling Engine"] },
    "sv01-144": { name: "Chansey", types: ["Colorless"], attacks: ["Pound","Egg Rolling"], abilities: [] },
    "sv01-145": { name: "Blissey", types: ["Colorless"], attacks: ["Happy Cyclone"], abilities: ["Busybody Nurse"] },
    "sv01-150": { name: "Staraptor", types: ["Colorless"], attacks: ["Tailspin Away","Power Blast"], abilities: [] },
    "sv01-151": { name: "Skwovet", types: ["Colorless"], attacks: ["Bite"], abilities: ["Nest Stash"] },
    "sv01-152": { name: "Greedent", types: ["Colorless"], attacks: ["Bite","Enhanced Fang"], abilities: [] },
    "sv01-157": { name: "Oinkologne", types: ["Colorless"], attacks: ["Ram","Leg Stomp"], abilities: [] },
    "sv01-160": { name: "Tandemaus", types: ["Colorless"], attacks: ["Double Hit"], abilities: [] },
    "sv01-167": { name: "Beach Court", types: [], attacks: [], abilities: [] },
    "sv01-168": { name: "Crushing Hammer", types: [], attacks: [], abilities: [] },
    "sv01-169": { name: "Defiance Band", types: [], attacks: [], abilities: [] },
    "sv01-170": { name: "Electric Generator", types: [], attacks: [], abilities: [] },
    "sv01-171": { name: "Energy Retrieval", types: [], attacks: [], abilities: [] },
    "sv01-172": { name: "Energy Search", types: [], attacks: [], abilities: [] },
    "sv01-173": { name: "Energy Switch", types: [], attacks: [], abilities: [] },
    "sv01-174": { name: "Exp. Share", types: [], attacks: [], abilities: [] },
    "sv01-175": { name: "Jacq", types: [], attacks: [], abilities: [] },
    "sv01-176": { name: "Judge", types: [], attacks: [], abilities: [] },
    "sv01-177": { name: "Katy", types: [], attacks: [], abilities: [] },
    "sv01-178": { name: "Mesagoza", types: [], attacks: [], abilities: [] },
    "sv01-179": { name: "Miriam", types: [], attacks: [], abilities: [] },
    "sv01-180": { name: "Nemona", types: [], attacks: [], abilities: [] },
    "sv01-181": { name: "Nest Ball", types: [], attacks: [], abilities: [] },
    "sv01-182": { name: "Pal Pad", types: [], attacks: [], abilities: [] },
    "sv01-184": { name: "Picnic Basket", types: [], attacks: [], abilities: [] },
    "sv01-185": { name: "Poké Ball", types: [], attacks: [], abilities: [] },
    "sv01-186": { name: "Pokégear 3.0", types: [], attacks: [], abilities: [] },
    "sv01-187": { name: "Pokémon Catcher", types: [], attacks: [], abilities: [] },
    "sv01-188": { name: "Potion", types: [], attacks: [], abilities: [] },
    "sv01-189": { name: "Professor's Research", types: [], attacks: [], abilities: [] },
    "sv01-191": { name: "Rare Candy", types: [], attacks: [], abilities: [] },
    "sv01-192": { name: "Rock Chestplate", types: [], attacks: [], abilities: [] },
    "sv01-193": { name: "Rocky Helmet", types: [], attacks: [], abilities: [] },
    "sv01-194": { name: "Switch", types: [], attacks: [], abilities: [] },
    "sv01-196": { name: "Ultra Ball", types: [], attacks: [], abilities: [] },
    "sv01-197": { name: "Vitality Band", types: [], attacks: [], abilities: [] },
    "sv01-198": { name: "Youngster", types: [], attacks: [], abilities: [] },
    "sv01-208": { name: "Pachirisu", types: ["Lightning"], attacks: ["Everyone Discharge"], abilities: ["Electricity Pouches"] },
    "sv01-209": { name: "Pawmot", types: ["Lightning"], attacks: ["Electro Paws"], abilities: ["Electrogenesis"] },
    "sv01-228": { name: "Gardevoir ex", types: ["Psychic"], attacks: ["Miracle Force"], abilities: ["Psychic Embrace"] },
    "sv01-245": { name: "Gardevoir ex", types: ["Psychic"], attacks: ["Miracle Force"], abilities: ["Psychic Embrace"] },
    "sv02-015": { name: "Meowscarada ex", types: ["Grass"], attacks: ["Scratching Nails"], abilities: ["Bouquet Magic"] },
    "sv02-016": { name: "Tarountula", types: ["Grass"], attacks: ["Bind Down"], abilities: [] },
    "sv02-026": { name: "Rellor", types: ["Grass"], attacks: ["Ball Roll"], abilities: [] },
    "sv02-027": { name: "Wo-Chien ex", types: ["Grass"], attacks: ["Covetous Ivy","Forest Blast"], abilities: [] },
    "sv02-028": { name: "Paldean Tauros", types: ["Fire"], attacks: ["Raging Horns","Blaze Dash"], abilities: [] },
    "sv02-030": { name: "Talonflame", types: ["Fire"], attacks: ["Clutch","Fiery Breeze"], abilities: [] },
    "sv02-035": { name: "Fuecoco", types: ["Fire"], attacks: ["Spacing Out","Flare"], abilities: [] },
    "sv02-037": { name: "Skeledirge ex", types: ["Fire"], attacks: ["Vitality Song","Burning Voice"], abilities: [] },
    "sv02-043": { name: "Gyarados", types: ["Water"], attacks: ["Revengeful Storm","Berserker Tackle"], abilities: [] },
    "sv02-048": { name: "Eiscue", types: ["Water"], attacks: ["Headbutt","Frigid Block"], abilities: [] },
    "sv02-055": { name: "Cetitan", types: ["Water"], attacks: ["Icicle Missile","Special Horn"], abilities: [] },
    "sv02-060": { name: "Baxcalibur", types: ["Water"], attacks: ["Buster Tail"], abilities: ["Super Cold"] },
    "sv02-061": { name: "Chien-Pao ex", types: ["Water"], attacks: ["Hail Blade"], abilities: ["Shivery Chill"] },
    "sv02-062": { name: "Pikachu", types: ["Lightning"], attacks: ["Growl","Pika Bolt"], abilities: [] },
    "sv02-063": { name: "Pikachu ex", types: ["Lightning"], attacks: ["Pika Punch","Dynamic Bolt"], abilities: [] },
    "sv02-072": { name: "Pincurchin", types: ["Lightning"], attacks: ["Needle Crush"], abilities: [] },
    "sv02-089": { name: "Spiritomb", types: ["Psychic"], attacks: ["Fade Out"], abilities: ["Fettered in Misfortune"] },
    "sv02-093": { name: "Dedenne ex", types: ["Psychic"], attacks: ["Tail Swap","Wondrous Shot"], abilities: [] },
    "sv02-094": { name: "Oranguru", types: ["Psychic"], attacks: ["Plotter's Command","Super Psy Bolt"], abilities: [] },
    "sv02-096": { name: "Palossand", types: ["Psychic"], attacks: ["Spooky Shot","Earthen Power"], abilities: [] },
    "sv02-097": { name: "Mimikyu", types: ["Psychic"], attacks: ["Ghost Eye"], abilities: ["Safeguard"] },
    "sv02-098": { name: "Ceruledge", types: ["Psychic"], attacks: ["Life Sucker","Fighting Sword"], abilities: [] },
    "sv02-105": { name: "Tinkaton", types: ["Psychic"], attacks: ["Special Hammer"], abilities: ["Gather Materials"] },
    "sv02-113": { name: "Hariyama", types: ["Fighting"], attacks: ["Rocket Slap"], abilities: ["Arm Thrust Practice"] },
    "sv02-117": { name: "Lycanroc ex", types: ["Fighting"], attacks: ["Rock Throw","Scary Fangs"], abilities: [] },
    "sv02-119": { name: "Falinks", types: ["Fighting"], attacks: ["Headbutt","Reckless Charge Together"], abilities: [] },
    "sv02-121": { name: "Nacli", types: ["Fighting"], attacks: ["Salt Coating","Tackle"], abilities: [] },
    "sv02-123": { name: "Garganacl", types: ["Fighting"], attacks: ["Knocking Hammer"], abilities: ["Blessed Salt"] },
    "sv02-126": { name: "Glimmora", types: ["Fighting"], attacks: ["Poison Petals"], abilities: ["Shattering Crystal"] },
    "sv02-127": { name: "Ting-Lu ex", types: ["Fighting"], attacks: ["Land Scoop"], abilities: ["Cursed Land"] },
    "sv02-130": { name: "Paldean Clodsire ex", types: ["Darkness"], attacks: ["Needle Bone"], abilities: ["Toxic Wetland"] },
    "sv02-136": { name: "Sableye", types: ["Darkness"], attacks: ["Night Eyes","Unseen Claw"], abilities: [] },
    "sv02-137": { name: "Seviper", types: ["Darkness"], attacks: ["Sharp Fang","Cross-Cut"], abilities: [] },
    "sv02-140": { name: "Hydreigon", types: ["Darkness"], attacks: ["Dark Cutter"], abilities: ["Tri Howl"] },
    "sv02-150": { name: "Copperajah ex", types: ["Metal"], attacks: ["Nosequake"], abilities: ["Bronze Body"] },
    "sv02-153": { name: "Noivern ex", types: ["Dragon"], attacks: ["Covert Flight","Dominating Echo"], abilities: [] },
    "sv02-170": { name: "Flamigo", types: ["Colorless"], attacks: ["United Wings"], abilities: ["Insta-Flock"] },
    "sv02-171": { name: "Artazon", types: [], attacks: [], abilities: [] },
    "sv02-172": { name: "Boss's Orders", types: [], attacks: [], abilities: [] },
    "sv02-173": { name: "Bravery Charm", types: [], attacks: [], abilities: [] },
    "sv02-175": { name: "Calamitous Wasteland", types: [], attacks: [], abilities: [] },
    "sv02-176": { name: "Choice Belt", types: [], attacks: [], abilities: [] },
    "sv02-179": { name: "Dendra", types: [], attacks: [], abilities: [] },
    "sv02-180": { name: "Falkner", types: [], attacks: [], abilities: [] },
    "sv02-181": { name: "Fighting Au Lait", types: [], attacks: [], abilities: [] },
    "sv02-182": { name: "Giacomo", types: [], attacks: [], abilities: [] },
    "sv02-183": { name: "Great Ball", types: [], attacks: [], abilities: [] },
    "sv02-184": { name: "Grusha", types: [], attacks: [], abilities: [] },
    "sv02-185": { name: "Iono", types: [], attacks: [], abilities: [] },
    "sv02-187": { name: "Saguaro", types: [], attacks: [], abilities: [] },
    "sv02-188": { name: "Super Rod", types: [], attacks: [], abilities: [] },
    "sv02-189": { name: "Superior Energy Retrieval", types: [], attacks: [], abilities: [] },
    "sv02-190": { name: "Jet Energy", types: [], attacks: [], abilities: [] },
    "sv02-191": { name: "Luminous Energy", types: [], attacks: [], abilities: [] },
    "sv02-193": { name: "Therapeutic Energy", types: [], attacks: [], abilities: [] },
    "sv02-255": { name: "Saguaro", types: [], attacks: [], abilities: [] },
    "sv02-270": { name: "Saguaro", types: [], attacks: [], abilities: [] },
    "sv03-003": { name: "Bellossom", types: ["Grass"], attacks: ["Sleep Powder","Powerful Dance"], abilities: [] },
    "sv03-004": { name: "Scyther", types: ["Grass"], attacks: ["Agility","Cut"], abilities: [] },
    "sv03-012": { name: "Trevenant", types: ["Grass"], attacks: ["Lock Up"], abilities: ["Forest Miasma"] },
    "sv03-029": { name: "Ninetales", types: ["Fire"], attacks: ["Will-O-Wisp","Nine-Tailed Dance"], abilities: [] },
    "sv03-030": { name: "Entei", types: ["Fire"], attacks: ["Blaze Ball"], abilities: ["Pressure"] },
    "sv03-035": { name: "Darmanitan", types: ["Fire"], attacks: ["Damage Counterpunch","Heat Blast"], abilities: [] },
    "sv03-036": { name: "Litwick", types: ["Fire"], attacks: ["Firebreathing"], abilities: [] },
    "sv03-042": { name: "Eiscue ex", types: ["Fire"], attacks: ["Scalding Block"], abilities: [] },
    "sv03-044": { name: "Armarouge", types: ["Fire"], attacks: ["Steam Artillery"], abilities: ["Scorching Armor"] },
    "sv03-050": { name: "Tympole", types: ["Water"], attacks: ["Screw Tail"], abilities: [] },
    "sv03-052": { name: "Seismitoad", types: ["Water"], attacks: ["Echoed Voice"], abilities: ["Quaking Zone"] },
    "sv03-054": { name: "Beartic", types: ["Water"], attacks: ["Icicle Punch","Frost Purge"], abilities: [] },
    "sv03-061": { name: "Finizen", types: ["Water"], attacks: ["Tail Smack"], abilities: [] },
    "sv03-062": { name: "Palafin", types: ["Water"], attacks: ["Jet Punch","Justice Kick"], abilities: [] },
    "sv03-066": { name: "Tyranitar ex", types: ["Lightning"], attacks: ["Mountain Hurl","Lightning Rampage"], abilities: [] },
    "sv03-070": { name: "Thundurus", types: ["Lightning"], attacks: ["Gigantic Bolt"], abilities: ["Adverse Weather"] },
    "sv03-076": { name: "Tadbulb", types: ["Lightning"], attacks: ["Shake and Discharge"], abilities: [] },
    "sv03-078": { name: "Bellibolt", types: ["Lightning"], attacks: ["Thunderous Edge"], abilities: ["Insulator"] },
    "sv03-082": { name: "Clefable ex", types: ["Psychic"], attacks: ["Wondrous Moon"], abilities: ["Lunar Zone"] },
    "sv03-086": { name: "Espeon", types: ["Psychic"], attacks: ["Psychic Assault","Psy Bolt"], abilities: [] },
    "sv03-098": { name: "Polteageist", types: ["Psychic"], attacks: ["Antique Collecting","Pour Tea"], abilities: [] },
    "sv03-101": { name: "Houndstone", types: ["Psychic"], attacks: ["Rear Kick","Two Four-ocious"], abilities: [] },
    "sv03-112": { name: "Stunfisk", types: ["Fighting"], attacks: ["Rumble"], abilities: ["Custom Trap"] },
    "sv03-116": { name: "Rockruff", types: ["Fighting"], attacks: ["Bite"], abilities: [] },
    "sv03-117": { name: "Lycanroc", types: ["Fighting"], attacks: ["Finishing Fang","Slashing Claw"], abilities: [] },
    "sv03-120": { name: "Klawf ex", types: ["Fighting"], attacks: ["Falling Press"], abilities: ["Counterattacking Pincer"] },
    "sv03-125": { name: "Charizard ex", types: ["Darkness"], attacks: ["Burning Darkness"], abilities: ["Infernal Reign"] },
    "sv03-128": { name: "Paldean Clodsire", types: ["Darkness"], attacks: ["Poison Ring","Muddy Hammer"], abilities: [] },
    "sv03-134": { name: "Houndoom ex", types: ["Darkness"], attacks: ["Evil Claw","Hound's Fang"], abilities: [] },
    "sv03-135": { name: "Absol ex", types: ["Darkness"], attacks: ["Future Sight","Cursed Slug"], abilities: [] },
    "sv03-142": { name: "Skarmory", types: ["Metal"], attacks: ["Peck","Slashing Steel"], abilities: [] },
    "sv03-143": { name: "Mawile", types: ["Metal"], attacks: ["Sharp Fang"], abilities: ["Special Eater"] },
    "sv03-145": { name: "Bronzong", types: ["Metal"], attacks: ["Oracle Press","Extrasensory"], abilities: [] },
    "sv03-151": { name: "Togedemaru", types: ["Metal"], attacks: ["Defense Curl","Rolling Tackle"], abilities: [] },
    "sv03-161": { name: "Drampa", types: ["Dragon"], attacks: ["Outrage"], abilities: [] },
    "sv03-169": { name: "Swablu", types: ["Colorless"], attacks: ["Fluffy Guard","Flap"], abilities: [] },
    "sv03-172": { name: "Stoutland", types: ["Colorless"], attacks: ["Chomp Chomp Panic","Sharp Fang"], abilities: [] },
    "sv03-174": { name: "Bouffalant", types: ["Colorless"], attacks: ["Damage Rush"], abilities: ["Bouffer"] },
    "sv03-178": { name: "Skwovet", types: ["Colorless"], attacks: ["Nicked Nibble","Gentle Slap"], abilities: [] },
    "sv03-179": { name: "Greedent ex", types: ["Colorless"], attacks: ["Never Ever Enough","Slip 'n' Roll"], abilities: [] },
    "sv03-183": { name: "Oinkologne", types: ["Colorless"], attacks: ["Confounding Cologne","High-Impact Kick"], abilities: [] },
    "sv03-187": { name: "Brassius", types: [], attacks: [], abilities: [] },
    "sv03-190": { name: "Ortega", types: [], attacks: [], abilities: [] },
    "sv03-192": { name: "Pokémon League Headquarters", types: [], attacks: [], abilities: [] },
    "sv03-193": { name: "Poppy", types: [], attacks: [], abilities: [] },
    "sv03-196": { name: "Town Store", types: [], attacks: [], abilities: [] },
    "sv03-197": { name: "Vengeful Punch", types: [], attacks: [], abilities: [] },
    "sv03-201": { name: "Bellibolt", types: ["Lightning"], attacks: ["Thunderous Edge"], abilities: ["Insulator"] },
    "sv03-219": { name: "Ortega", types: [], attacks: [], abilities: [] },
    "sv06.5-002": { name: "Galvantula", types: ["Grass"], attacks: ["Shocking Web"], abilities: ["Compound Eyes"] },
    "sv06.5-008": { name: "Houndoom", types: ["Fire"], attacks: ["Bite","Snarl"], abilities: [] },
    "sv06.5-015": { name: "Revavroom ex", types: ["Lightning"], attacks: ["Accelerator Flash","Shattering Speed"], abilities: [] },
    "sv06.5-021": { name: "Cresselia", types: ["Psychic"], attacks: ["Healing Pirouette","Crescent Purge"], abilities: [] },
    "sv06.5-025": { name: "Bloodmoon Ursaluna", types: ["Fighting"], attacks: ["Mad Bite"], abilities: ["Battle-Hardened"] },
    "sv06.5-026": { name: "Slither Wing", types: ["Fighting"], attacks: ["Iron Smasher","Smashing Wing"], abilities: [] },
    "sv06.5-030": { name: "Absol", types: ["Darkness"], attacks: ["Darkfall"], abilities: [] },
    "sv06.5-036": { name: "Okidogi ex", types: ["Darkness"], attacks: ["Poisonous Musculature","Chain-Crazed"], abilities: [] },
    "sv06.5-037": { name: "Munkidori ex", types: ["Darkness"], attacks: ["Dirty Headbutt"], abilities: ["Oh No You Don't"] },
    "sv06.5-038": { name: "Fezandipiti ex", types: ["Darkness"], attacks: ["Cruel Arrow"], abilities: ["Flip the Script"] },
    "sv06.5-039": { name: "Pecharunt ex", types: ["Darkness"], attacks: ["Irritated Outburst"], abilities: ["Subjugating Chains"] },
    "sv06.5-043": { name: "Varoom", types: ["Metal"], attacks: ["Rigidify","Headbutt Bounce"], abilities: [] },
    "sv06.5-048": { name: "Meowth", types: ["Colorless"], attacks: ["Fury Swipes"], abilities: [] },
    "sv06.5-059": { name: "Janine's Secret Art", types: [], attacks: [], abilities: [] },
    "sv06.5-060": { name: "Neutralization Zone", types: [], attacks: [], abilities: [] },
    "sv06.5-096": { name: "Earthen Vessel", types: [], attacks: [], abilities: [] },
    "swsh10.5-009": { name: "Charmeleon", types: ["Fire"], attacks: ["Scratch","Flamethrower"], abilities: [] },
    "swsh10.5-010": { name: "Charizard", types: ["Fire"], attacks: ["Flare Blitz"], abilities: ["Burn Brightly"] },
    "swsh10.5-011": { name: "Radiant Charizard", types: ["Fire"], attacks: ["Combustion Blast"], abilities: ["Excited Heart"] },
    "swsh10.5-018": { name: "Radiant Blastoise", types: ["Water"], attacks: ["Torrential Cannon"], abilities: ["Pump Shot"] },
    "swsh10.5-022": { name: "Gyarados", types: ["Water"], attacks: ["Wreak Havoc","Wild Splash"], abilities: [] },
    "swsh10.5-025": { name: "Wimpod", types: ["Water"], attacks: ["Gnaw"], abilities: ["Punk Out"] },
    "swsh10.5-026": { name: "Golisopod", types: ["Water"], attacks: ["First Impression","Slash"], abilities: [] },
    "swsh10.5-027": { name: "Pikachu", types: ["Lightning"], attacks: ["Buddy Bolt"], abilities: [] },
    "swsh10.5-031": { name: "Mewtwo VSTAR", types: ["Psychic"], attacks: ["Psy Purge","Star Raid"], abilities: [] },
    "swsh10.5-032": { name: "Natu", types: ["Psychic"], attacks: ["Nap","Peck"], abilities: [] },
    "swsh10.5-035": { name: "Sylveon", types: ["Psychic"], attacks: ["Souvenir","Wonder Flash"], abilities: [] },
    "swsh10.5-036": { name: "Onix", types: ["Fighting"], attacks: ["Rock Tomb","Raging Swing"], abilities: [] },
    "swsh10.5-043": { name: "Tyranitar", types: ["Darkness"], attacks: ["Raging Crash","Earthquake"], abilities: [] },
    "swsh10.5-055": { name: "Snorlax", types: ["Colorless"], attacks: ["Collapse"], abilities: ["Block"] },
    "swsh10.5-061": { name: "Pidove", types: ["Colorless"], attacks: ["Growl","Flap"], abilities: [] },
  } as Record<string, { name: string; types: string[]; attacks: string[]; abilities: string[] }>,
  /** Real-card fixture ids with NO catalog row at all — the population D154 found
      and D156 enumerated at TWELVE, every one `swsh10.5`. **EMPTY since D160's
      re-ingest**, and the emptiness is the finding: those twelve were the only
      surviving copies of catalog rows nothing could check, and their "verbatim off
      the local D1" doc blocks became checkable for the first time. Kept as a field
      rather than deleted because a fixture id with no row is exactly the defect
      this manifest exists to surface, and a list that can only ever be empty is
      one nobody re-reads. */
  absent: [] as readonly string[],
} as const;
