vim.keymap.set("n", "<A-!>", "<cmd>silent! !switch_tmux_session 1<CR>", { silent = true })
vim.keymap.set("n", "<A-@>", "<cmd>silent! !switch_tmux_session 2<CR>", { silent = true })
vim.keymap.set("n", "<A-#>", "<cmd>silent! !switch_tmux_session 3<CR>", { silent = true })
vim.keymap.set("n", "<A-$>", "<cmd>silent! !switch_tmux_session 4<CR>", { silent = true })
vim.keymap.set("n", "<A-%>", "<cmd>silent! !switch_tmux_session 5<CR>", { silent = true })
vim.keymap.set("n", "<A-^>", "<cmd>silent! !switch_tmux_session 6<CR>", { silent = true })
