DBEE_CONNECTIONS: ENC[AES256_GCM,data:VluFqwoSfABC4DwxSXUs5i1TKbniF+94stlF5H5Px8/r74P8kG91UoXYdB0YfZeBY1bpdsoaBpPSaUy/dPLL/9xq3VFpjTfdiK2tl9BR8fDxRpiciXknKhq7sNIsiInC3TxluQ33fcHPcDbhL8wcrqoq3p7e2h4rOAFQagImELBtP2zulCR00jP2FiRfyIBX/R6t1Awe4ZOr+5l7w565AvdhB2H4ZPm+hi88WqWHyhpr30AH5K0bpmg4MHmhxQDBy6cRuo43iq8MCBtV0QEv+1t9exakInZi/QR9pUeVrnTZyUtlRIMlBlfel+uHOKhNcccgmKBhgrCbn9kDplZ0EHxC8wXOKyMD/LjY4/L/Pvpg/FfIZIeBiY12ZwGc5Pk1CP9Eke0H6FipWOWk8zAxYdtIUYzZuncW2x0vuIfuSGWm1JXDlO/RC6d3VICeLrQIUCw/hyFajDcRtDRfv5gtgIeWbV+TOlawvn6DLhPEynZW9x1q8i2h7PR4JKHCcoSxrJ1LhMbNTac5PhvcGX2Hg4yYhB/p5sHpilFfW6E6u/Th4b0zIXiXQ9XsNEJpvnBZ9V++qOLuahHTqPMAOOZkRSmaeqxhduSGtrWuI0ZOHfPSKAX4Jm/3SrkFX3jrLPls9KHQtgE1kDzs6ogHSHHZl4ocNKH7bRaEDOtyuUQuoJMRrXxC1fH/GRfU+f7eU9n4uNH1a1oJ2CjI2/jtMKk=,iv:T1Bv1TziX0AeVhgt5UXeDfUb+8rWsXKnbZ5dkx07zYg=,tag:hgfzLdBSGJSESryn5ln5iw==,type:str]
sops:
    age:
        - recipient: age12wc82encjxm5sc5l3nez93ewtr5kujz7p79gc2wj5yquk4460ems7ds7up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeTFvY3BmQ1RzL3VBTVM5
            U21rbjFCQnMvOExZNWxnUDkxdjgzazlYblVBCjY4NW9MRlVCeEt4bVd1VERMWVRY
            K25ncFI2SEZ2aklRci9Bb0hUVzZ0VkEKLS0tIEI4cldUUC9malc0dGR3aHRMaXRS
            TmhOb3VGNmNTKy9OWm1XZ0dneWluek0KWRSLw5mhG5b6Lx9WPBKVPQ+kPVW+LDLp
            XqPnTtz3VvrOzMeRVN9gru+owGDEDks/W/IsQ/1Rf/ry9um1LcJc/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T09:38:56Z"
    mac: ENC[AES256_GCM,data:sXHJSdNePJ7cq94uJLA1XKFirARy9qaVNK4cwuQ4O4AQGtZMW1yur2dt47mL/X4D54zLBLbXLphRzbqqjcg6GL2D62lSX37q7QNkT1OcGoQZBJaa2cj1Rlb7F7Nz4UJReJgJiqsyCBg/mLTHhozF/QC9jXgZ79hMw+UIX6YlZi8=,iv:iOmqgoHnZWhpKz52Z84tkimOSdstWBPkftw9v/ZYVdI=,tag:6AyVxUwG9b00XM3a7bwTKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
