-- telescope.nvim (disabled — replaced by snacks.picker)
-- local actions = require("telescope.actions")
-- require("telescope").setup({
--   defaults = {
--     hidden = true,
--     file_ignore_patterns = {
--       "%.git/",
--       "%.wrangler/",
--       "%.vscode/",
--       "%.vite/",
--       "dist/",
--       "^storage/",
--       "^public/",
--       "^public_html/",
--       "^node_modules/",
--       "^assets/",
--       "^database/migrations/",
--       "^bootstrap/",
--       "^vendor/",
--       "^android/",
--       "^ios/",
--       "^neo4j/",
--       "^test/",
--     },
--     mappings = {
--       n = {
--         ["q"] = actions.close,
--       },
--       i = {
--         ["<A-c>"] = actions.delete_buffer,
--         ["<A-v>"] = actions.select_vertical,
--         ["<A-x>"] = actions.select_horizontal,
--         ["<A-q>"] = actions.smart_send_to_qflist,
--         ["<A-o>"] = actions.cycle_history_prev,
--         ["<A-i>"] = actions.cycle_history_next,
--       },
--     },
--     layout_config = { width = 190, height = 45 },
--   },
--   pickers = {
--     find_files = {
--       hidden = true,
--       no_ignore = true,
--       no_ignore_parent = true,
--     },
--   },
-- })
--
-- local builtin = require("telescope.builtin")
-- local map = vim.keymap.set
-- map("n", "<A-o>", builtin.find_files)
-- map("n", "<A-g>", builtin.live_grep)
-- map("n", "<A-c>", builtin.git_status)
-- map("n", "<space><space>", builtin.resume)
