[sftp.myclientum]
type = "sftp"
host = "dev.myclientum.com"
user = "dev_myclientum_com"
port = 22

[sftp.tacprod]
type = "sftp"
host = "dev2.tacprod.cat"
user = "dev_tacprod_cat"
port = 22

[sftp.compartium]
type = "sftp"
host = "app.compartium.cat"
user = "app_compartium_cat"
port = 22
