-- vim.cmd([[autocmd FileType markdown setlocal colorcolumn=93]])
-- vim.cmd([[autocmd FileType markdown setlocal textwidth=90]])
--
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "*",
--   callback = function()
--     vim.opt_local.formatoptions:remove({ 'c', 'r', 'o' })
--   end,
-- })
--
-- vim.cmd[[
--     augroup remember_folds
--       autocmd!
--       au BufWinLeave ?* mkview 1
--       au BufWinEnter ?* silent! loadview 1 | setlocal foldlevel=0
--     augroup END
-- ]]
