set -s escape-time 0
set -g allow-rename off
set -g base-index 1
set -s set-clipboard on
set -g mouse on 
set -g focus-events on
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",foot:Tc"
set -ga terminal-overrides ",foot:RGB"
set-hook -g after-new-session 'rename-window "editor"'

unbind-key -a
set -g prefix C-b

bind -n M-Enter new-window -c "#{pane_current_path}"
bind -n M-q kill-window 

bind -n M-1 if-shell 'tmux select-window -t 1' '' 'new-window -t 1 -n "editor" -c "#{pane_current_path}"'
bind -n M-2 if-shell 'tmux select-window -t 2' '' 'new-window -t 2 -n "claude" -c "#{pane_current_path}"'
bind -n M-3 if-shell 'tmux select-window -t 3' '' 'new-window -t 3 -n "terminal" -c "#{pane_current_path}"'
bind -n M-4 if-shell 'tmux select-window -t 4' '' 'new-window -t 4 -n "vpn" -c "#{pane_current_path}"'

# bind -n M-o switch-client -n
# bind -n M-i switch-client -p

# bind -n M-s run-shell "tmux neww ~/.dotfiles/scripts/tmux-sessionizer.sh"

bind -n M-s display-popup -E -w 30% -h 60% "~/.dotfiles/scripts/tmux-sessionizer.sh"

set -g status-position top
set -g status-left-length 50
set -g status-left "[#S] "
set -g status-right ""
set -g status-style 'fg=#8A86A3,bg=#232136'
set -g window-status-format " #W"
set -g window-status-current-format " #W"
set -g window-status-current-style 'fg=#CCC9E0'
